# Generated by Django 4.0.5 on 2022-06-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Master_String', models.CharField(max_length=50)),
                ('String1', models.CharField(max_length=50)),
                ('String2', models.CharField(max_length=50)),
                ('String3', models.CharField(max_length=50)),
                ('String4', models.CharField(max_length=50)),
            ],
        ),
    ]
